### ISSUE TITLE
fatal compilation error: call to 'abs' is ambiguous

### ISSUE THREAD

**Issue by DuckSoft** [nu-book/zxing-cpp#143]
> TL;DR: possibly another missing header: `<cmath>` 

I encountered this problem when compiling [Qv2ray](https://github.com/Qv2ray/Qv2ray) on Azure macOS 10.14, using AppleClang 11.0.0.11000033 with Xcode 11.3.1, where I have just upgraded our submodule zxing-cpp to commit hash 5351b67eac63c7e544274abf5b15b55c7716a6cf.

Since we are about to release our new version, I did a series of git bisect to locate the problem, listed as follows.
You can check these out on https://dev.azure.com/realducksoft/Qv2ray/_build?definitionId=3&branchFilter=62%2C62%2C62%2C62%2C62%2C62%2C62.

```diff
git bisect start
# bad: [5351b67eac63c7e544274abf5b15b55c7716a6cf] PDFCodewordDecoder.cpp: uint16_t requires cstdint (#141)
git bisect bad 5351b67eac63c7e544274abf5b15b55c7716a6cf
# good: [66cc26b25633cb7f1e20f2bf7711960c321e3a7b] Pump version to 1.0.8
git bisect good 66cc26b25633cb7f1e20f2bf7711960c321e3a7b
# good: [a1c9b6eb86ce725631125cc6d0faa59760a10c2a] BarcodeFormat: fix bug in string conversion of BarcodeFormat::INVALID
git bisect good a1c9b6eb86ce725631125cc6d0faa59760a10c2a
# good: [23a00f3767a1c94949478bcbd31961387a1d682a] ZXAlgos: rename Accumulate to Reduce + default 0 + optional op parameter
git bisect good 23a00f3767a1c94949478bcbd31961387a1d682a
# good: [cdae128138a7a401753033f9d3308374f1ee821a] 1D: add/modify codabar blackbox samples to over more real world use cases
git bisect good cdae128138a7a401753033f9d3308374f1ee821a
# bad: [8e5f8cf7573718078333615815e93aa04695be3a] WIP: improved naming and documentation related to new Pattern abstraction
git bisect bad 8e5f8cf7573718078333615815e93aa04695be3a
# good: [24f3454c0eebba6231568bf2ec13ae7d7369a9f1] Size(): replace static_cast<int>(... .size()|.length()) with new Size()
git bisect good 24f3454c0eebba6231568bf2ec13ae7d7369a9f1
# bad: [5566db9885b6bf8d40de64c50db5d65d7a29d484] WIP: introduce new infrastructure and algorithms for the 1D RowReaders
git bisect bad 5566db9885b6bf8d40de64c50db5d65d7a29d484
```

And here is the git bisect bad commit 5566db9885b6bf8d40de64c50db5d65d7a29d484 report, whose author is @axxel:
```diff
5566db9885b6bf8d40de64c50db5d65d7a29d484 is the first bad commit
commit 5566db9885b6bf8d40de64c50db5d65d7a29d484
Author: Axel Waggershauser <awagger@gmail.com>
Date:   Mon Jul 6 17:27:21 2020 +0200

    WIP: introduce new infrastructure and algorithms for the 1D RowReaders
    
    Instead of working on `BitArray` and count consecutive 1s and 0s in each
    `RowReader` implementation, we can do that once and work on ints instead.
    
    This commit also includes new algorithms for the 3 codes based on two level
    bar codes (only narrow and wide bars/spaces). ITF, Codabar and Code39 are
    now based on the same code and about 10x faster than before. Also Codabar
    works on more samples.
    
    The new code is currently disabled. See ZXConfig.h. There is code to
    support both old and new `ODRowReader`s during a transition period. The
    full performance benefit will be realized, once the old `BitArray`
    version can be dropped.

 core/CMakeLists.txt                   |   1 +
 core/src/BinaryBitmap.h               |  22 ++++
 core/src/DecodeStatus.h               |   5 +
 core/src/GlobalHistogramBinarizer.cpp |  47 ++++++++
 core/src/GlobalHistogramBinarizer.h   |   1 +
 core/src/Pattern.h                    | 204 ++++++++++++++++++++++++++++++++++
 core/src/ZXConfig.h                   |   6 +
 core/src/oned/ODCodabarReader.cpp     |  74 ++++++++++--
 core/src/oned/ODCodabarReader.h       |   1 +
 core/src/oned/ODCode39Reader.cpp      |  63 ++++++++++-
 core/src/oned/ODCode39Reader.h        |   1 +
 core/src/oned/ODITFReader.cpp         |  55 +++++++++
 core/src/oned/ODITFReader.h           |   1 +
 core/src/oned/ODReader.cpp            |  21 ++++
 core/src/oned/ODRowReader.cpp         |   9 ++
 core/src/oned/ODRowReader.h           |  68 +++++++++++-
 test/blackbox/BlackboxTestRunner.cpp  |  10 ++
 17 files changed, 578 insertions(+), 11 deletions(-)
 create mode 100644 core/src/Pattern.h
```

something that maybe helpful: https://en.cppreference.com/w/cpp/numeric/math/fabs

---
attachment: two bad bisect logs

<details>

@ git bisect bad 5351b67eac63c7e544274abf5b15b55c7716a6cf
```
2020-07-13T17:05:20.7845210Z FAILED: CMakeFiles/qv2ray-zxing.dir/3rdparty/zxing-cpp/core/src/oned/ODRSSExpandedReader.cpp.o 
2020-07-13T17:05:20.7951090Z /Applications/Xcode_11.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DNODE_EDITOR_EXPORTS -DNODE_EDITOR_SHARED -DQAPPLICATION_CLASS=QApplication -DQV2RAY_QWIDGETS -DQV2RAY_VERSION_BUGFIX=1 -DQV2RAY_VERSION_BUILD=5779 -DQV2RAY_VERSION_MAJOR=2 -DQV2RAY_VERSION_MINOR=6 -DQV2RAY_VERSION_STRING=\"2.6.1\" -D_QV2RAY_BUILD_EXTRA_INFO_STR_="\"Qv2ray 2.6.1:5779\"" -D_QV2RAY_BUILD_INFO_STR_="\"Qv2ray from manual build\"" -I. -I../ -Iqv2ray-zxing_autogen/include -I../3rdparty/zxing-cpp/core/src -I../3rdparty/zxing-cpp/core/src/aztec -I../3rdparty/zxing-cpp/core/src/datamatrix -I../3rdparty/zxing-cpp/core/src/maxicode -I../3rdparty/zxing-cpp/core/src/oned -I../3rdparty/zxing-cpp/core/src/oned/rss -I../3rdparty/zxing-cpp/core/src/pdf417 -I../3rdparty/zxing-cpp/core/src/qrcode -I../3rdparty/zxing-cpp/core/src/textcodec -O3 -DNDEBUG -isysroot /Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13   -std=gnu++17 -MD -MT CMakeFiles/qv2ray-zxing.dir/3rdparty/zxing-cpp/core/src/oned/ODRSSExpandedReader.cpp.o -MF CMakeFiles/qv2ray-zxing.dir/3rdparty/zxing-cpp/core/src/oned/ODRSSExpandedReader.cpp.o.d -o CMakeFiles/qv2ray-zxing.dir/3rdparty/zxing-cpp/core/src/oned/ODRSSExpandedReader.cpp.o -c ../3rdparty/zxing-cpp/core/src/oned/ODRSSExpandedReader.cpp
2020-07-13T17:05:20.8048300Z In file included from ../3rdparty/zxing-cpp/core/src/oned/ODRSSExpandedReader.cpp:18:
2020-07-13T17:05:20.8150570Z In file included from ../3rdparty/zxing-cpp/core/src/oned/ODRSSExpandedReader.h:19:
2020-07-13T17:05:20.8247130Z ../3rdparty/zxing-cpp/core/src/oned/rss/../ODRowReader.h:187:21: error: call to 'abs' is ambiguous
2020-07-13T17:05:20.8248820Z                         float variance = std::abs(counters[x] - pattern[x] * unitBarWidth);
2020-07-13T17:05:20.8249590Z                                          ^~~~~~~~
2020-07-13T17:05:20.8251040Z ../3rdparty/zxing-cpp/core/src/oned/rss/../ODRowReader.h:199:10: note: in instantiation of function template specialization 'ZXing::OneD::RowReader::PatternMatchVariance<int, int>' requested here
2020-07-13T17:05:20.8252220Z                 return PatternMatchVariance(counters.data(), pattern.data(), counters.size(), maxIndividualVariance);
2020-07-13T17:05:20.8252920Z                        ^
2020-07-13T17:05:20.8254380Z ../3rdparty/zxing-cpp/core/src/oned/rss/ODRSSReaderHelper.h:42:19: note: in instantiation of function template specialization 'ZXing::OneD::RowReader::PatternMatchVariance<std::__1::array<int, 4>, std::__1::array<int, 4> >' requested here
2020-07-13T17:05:20.8255730Z                         if (RowReader::PatternMatchVariance(counters, finderPatterns[value], MAX_INDIVIDUAL_VARIANCE) < MAX_AVG_VARIANCE) {
2020-07-13T17:05:20.8256530Z                                        ^
2020-07-13T17:05:20.8258090Z ../3rdparty/zxing-cpp/core/src/oned/ODRSSExpandedReader.cpp:163:28: note: in instantiation of function template specialization 'ZXing::OneD::RSS::ReaderHelper::ParseFinderValue<std::__1::array<int, 4>, std::__1::array<std::__1::array<int, 4>, 6> >' requested here
2020-07-13T17:05:20.8267830Z         int value = ReaderHelper::ParseFinderValue(counters, FINDER_PATTERNS);
2020-07-13T17:05:20.8369780Z                                   ^
2020-07-13T17:05:20.8461590Z /Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:132:6: note: candidate function
2020-07-13T17:05:20.8472650Z int      abs(int) __pure2;
2020-07-13T17:05:20.8473400Z          ^
2020-07-13T17:05:20.8474190Z /Applications/Xcode_11.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdlib.h:111:44: note: candidate function
2020-07-13T17:05:20.8475050Z inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT {return  labs(__x);}
2020-07-13T17:05:20.8475750Z                                            ^
2020-07-13T17:05:20.8476570Z /Applications/Xcode_11.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdlib.h:113:44: note: candidate function
2020-07-13T17:05:20.8477930Z inline _LIBCPP_INLINE_VISIBILITY long long abs(long long __x) _NOEXCEPT {return llabs(__x);}
2020-07-13T17:05:20.8478660Z                                            ^
2020-07-13T17:05:20.8479220Z 1 error generated.
```

@ git bisect bad 8e5f8cf7573718078333615815e93aa04695be3a:
```
2020-07-13T18:16:39.4716920Z FAILED: CMakeFiles/qv2ray-zxing.dir/3rdparty/zxing-cpp/core/src/oned/ODCode39Reader.cpp.o 
2020-07-13T18:16:39.4822380Z /Applications/Xcode_11.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DNODE_EDITOR_EXPORTS -DNODE_EDITOR_SHARED -DQAPPLICATION_CLASS=QApplication -DQV2RAY_QWIDGETS -DQV2RAY_VERSION_BUGFIX=1 -DQV2RAY_VERSION_BUILD=5776 -DQV2RAY_VERSION_MAJOR=2 -DQV2RAY_VERSION_MINOR=6 -DQV2RAY_VERSION_STRING=\"2.6.1\" -D_QV2RAY_BUILD_EXTRA_INFO_STR_="\"Qv2ray 2.6.1:5776\"" -D_QV2RAY_BUILD_INFO_STR_="\"Qv2ray from manual build\"" -I. -I../ -Iqv2ray-zxing_autogen/include -I../3rdparty/zxing-cpp/core/src -I../3rdparty/zxing-cpp/core/src/aztec -I../3rdparty/zxing-cpp/core/src/datamatrix -I../3rdparty/zxing-cpp/core/src/maxicode -I../3rdparty/zxing-cpp/core/src/oned -I../3rdparty/zxing-cpp/core/src/oned/rss -I../3rdparty/zxing-cpp/core/src/pdf417 -I../3rdparty/zxing-cpp/core/src/qrcode -I../3rdparty/zxing-cpp/core/src/textcodec -O3 -DNDEBUG -isysroot /Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13   -std=gnu++17 -MD -MT CMakeFiles/qv2ray-zxing.dir/3rdparty/zxing-cpp/core/src/oned/ODCode39Reader.cpp.o -MF CMakeFiles/qv2ray-zxing.dir/3rdparty/zxing-cpp/core/src/oned/ODCode39Reader.cpp.o.d -o CMakeFiles/qv2ray-zxing.dir/3rdparty/zxing-cpp/core/src/oned/ODCode39Reader.cpp.o -c ../3rdparty/zxing-cpp/core/src/oned/ODCode39Reader.cpp
2020-07-13T18:16:39.4879190Z In file included from ../3rdparty/zxing-cpp/core/src/oned/ODCode39Reader.cpp:18:
2020-07-13T18:16:39.4929520Z In file included from ../3rdparty/zxing-cpp/core/src/oned/ODCode39Reader.h:19:
2020-07-13T18:16:39.4943700Z In file included from ../3rdparty/zxing-cpp/core/src/oned/ODRowReader.h:22:
2020-07-13T18:16:39.5040250Z ../3rdparty/zxing-cpp/core/src/Pattern.h:179:8: error: call to 'abs' is ambiguous
2020-07-13T18:16:39.5066020Z                         if (std::abs(view[x] - pattern[x] * moduleSize) > moduleSizeRef / 2)
2020-07-13T18:16:39.5167210Z                             ^~~~~~~~
2020-07-13T18:16:39.5178780Z ../3rdparty/zxing-cpp/core/src/Pattern.h:207:42: note: in instantiation of function template specialization 'ZXing::IsPattern<9, 6>' requested here
2020-07-13T18:16:39.5220070Z                 view, [&pattern](auto window) { return IsPattern(window, pattern); }, quiteZoneScale);
2020-07-13T18:16:39.5236220Z                                                        ^
2020-07-13T18:16:39.5322750Z ../3rdparty/zxing-cpp/core/src/Pattern.h:206:9: note: in instantiation of function template specialization 'ZXing::FindPattern<9, (lambda at ../3rdparty/zxing-cpp/core/src/Pattern.h:207:9)>' requested here
2020-07-13T18:16:39.5344690Z         return FindPattern<LEN>(
2020-07-13T18:16:39.5347160Z                ^
2020-07-13T18:16:39.5348700Z ../3rdparty/zxing-cpp/core/src/oned/ODCode39Reader.cpp:227:21: note: in instantiation of function template specialization 'ZXing::FindPattern<9, 6, true>' requested here
2020-07-13T18:16:39.5350250Z         auto next = ZXing::FindPattern(row.subView(0, -minCharCount * CHAR_LEN), START_PATTERN, QUITE_ZONE_SCALE);
2020-07-13T18:16:39.5350980Z                            ^
2020-07-13T18:16:39.5351800Z /Applications/Xcode_11.3.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/stdlib.h:132:6: note: candidate function
2020-07-13T18:16:39.5352580Z int      abs(int) __pure2;
2020-07-13T18:16:39.5353030Z          ^
2020-07-13T18:16:39.5353800Z /Applications/Xcode_11.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdlib.h:111:44: note: candidate function
2020-07-13T18:16:39.5354690Z inline _LIBCPP_INLINE_VISIBILITY long      abs(     long __x) _NOEXCEPT {return  labs(__x);}
2020-07-13T18:16:39.5355330Z                                            ^
2020-07-13T18:16:39.5356150Z /Applications/Xcode_11.3.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdlib.h:113:44: note: candidate function
2020-07-13T18:16:39.5357050Z inline _LIBCPP_INLINE_VISIBILITY long long abs(long long __x) _NOEXCEPT {return llabs(__x);}
2020-07-13T18:16:39.5357710Z                                            ^
2020-07-13T18:16:39.5358210Z 1 error generated.
```

</details>

**Comment by axxel** [comment]
Thanks for the feedback. I'll fix that shortly. I appreciate people testing the current WIP but would not generally advice release that code at the moment. Note that we have not tagged it as a release and the API is definitively not stable. (See, e.g. the INVALID -> NONE rename I just commited).

**Comment by DuckSoft** [comment]
After switching to a recent commit hash 6369cb9d1525b1b2cf0890b51b1d1a7871b2fa38, we can finally build without any error. Thank you for the timely response! 

We understand that we are having risk breaking our API when following the bleeding-edge of upstream. We think that it will be worthy, since we can act as another kind of "Continous Integration" to help upstream improve the code from time to time. 

Thanks for the great project you've maintained! Cheers!
